azureADClient:
  pullInterval: 300
  tenantId: "c96a62e5-1e49-4187-b394-08b694e8bb0d"
  clientId: "7b641758-f26e-499f-9698-420fe8d6115e"
  clientSecret: "o:.vB7XHsGT0_Mgc[JVD7ep1d3rao[nS"

senderParams:
  accountToken: "oCwtQDtWjDOMcHXHGGNrnRgkEMxCDuiO"
  debug: true
