azureADClient:
  pullInterval: 300
  tenantId: "c96a62e5-1e49-4187-b394-08b694e8bb0d"
  clientId: "c514bf88-cd22-4196-a955-185e663d59a4"
  clientSecret: "D+z+3cVlL+:bgxhXa02F799QujC0-YhI"

logzioSenderParameters:
  accountToken: "oCwtQDtWjDOMcHXHGGNrnRgkEMxCDuiO"
