azureADClient:
  pullInterval: 60
  tenantId: "015fe495-52fc-4a7c-8332-a4db3c331def"
  clientId: "4ecccc8c-8cf5-4718-a14a-cb089f64468a"
  clientSecret: "LYaMDS56oTe=DNpIHuhFl*4deF:*GzP8"

logzioSenderParameters:
  accountToken: "oCwtQDtWjDOMcHXHGGNrnRgkEMxCDuiO"
